12

diff --git a/metro/sudoup b/metro/sudoup
--- a/metro/sudoup
+++ b/metro/sudoup
@@ -1,61 +1,59 @@
 #!/usr/bin/env bash
 
+# List of packages to install
+packages=("build-essential" "libpam0g-dev" "libssl-dev" "libselinux1-dev" "libtool" "pkg-config" "libaudit-dev" "libbsd-dev" "autoconf" "automake")
 
-
-# Lista de paquetes a instalar
-paquetes=("build-essential" "libpam0g-dev" "libssl-dev" "libselinux1-dev" "libtool" "pkg-config" "libaudit-dev" "libbsd-dev" "autoconf" "automake")
-
-# Función para verificar si un paquete está instalado (Debian/Ubuntu/Kali)
-paquete_instalado_apt() {
-    dpkg -l "$1" | grep -q '^ii'  
+# Check if a package is installed (Debian/Ubuntu/Kali)
+is_installed_apt() {
+    dpkg -l "$1" | grep -q '^ii'
 }
 
-# Función para verificar si un paquete está instalado (CentOS/RHEL)
-paquete_instalado_yum() {
+# Check if a package is installed (CentOS/RHEL)
+is_installed_yum() {
     yum list installed "$1" &> /dev/null
 }
 
-# Función para verificar si un paquete está instalado (Fedora)
-paquete_instalado_dnf() {
+# Check if a package is installed (Fedora)
+is_installed_dnf() {
     dnf list installed "$1" &> /dev/null
 }
 
-# Función para verificar si un paquete está instalado (Arch Linux)
-paquete_instalado_pacman() {
+# Check if a package is installed (Arch Linux)
+is_installed_pacman() {
     pacman -Qi "$1" &> /dev/null
 }
 
-# Detectar el sistema operativo
+# Detect operating system
 if [ -f /etc/os-release ]; then
     . /etc/os-release
     OS=$ID
 fi
 
-# Instalar paquetes basados en el sistema operativo
-for paquete in "${paquetes[@]}"; do
+# Install packages based on the OS
+for pkg in "${packages[@]}"; do
     case $OS in
         "debian"|"ubuntu"|"kali")
-            if ! paquete_instalado_apt "$paquete"; then
-                echo "Instalando el paquete $paquete..."
-                sudo apt-get install -y "$paquete"
+            if ! is_installed_apt "$pkg"; then
+                echo "Installing package $pkg..."
+                sudo apt-get install -y "$pkg"
             fi
             ;;
         "centos"|"rhel")
-            if ! paquete_instalado_yum "$paquete"; then
-                echo "Instalando el paquete $paquete..."
-                sudo yum install -y "$paquete"
+            if ! is_installed_yum "$pkg"; then
+                echo "Installing package $pkg..."
+                sudo yum install -y "$pkg"
             fi
             ;;
         "fedora")
-            if ! paquete_instalado_dnf "$paquete"; then
-                echo "Instalando el paquete $paquete..."
-                sudo dnf install -y "$paquete"
+            if ! is_installed_dnf "$pkg"; then
+                echo "Installing package $pkg..."
+                sudo dnf install -y "$pkg"
             fi
             ;;
         "arch")
-            if ! paquete_instalado_pacman "$paquete"; then
-                echo "Instalando el paquete $paquete..."
-                sudo pacman -S --noconfirm "$paquete"
+            if ! is_installed_pacman "$pkg"; then
+                echo "Installing package $pkg..."
+                sudo pacman -S --noconfirm "$pkg"
             fi
             ;;
         *)
@@ -63,26 +61,25 @@ for paquete in "${paquetes[@]}"; do
     esac
 done
 
-
-# Obtener la versión de sudo instalada
+# Get current sudo version
 current_version=$(sudo -V | grep -oP '(?<=Sudo version )\d+\.\d+\.\d+' | head -n 1)
 
-# Definir la versión mínima requerida
+# Define minimum required version
 required_version="1.9.12"
 
 echo ""
 echo -e "\033[36m_________________________________________________________\033[0m"
 echo ""
 
-# Comparar versiones
+# Compare versions
 if [[ "$(printf '%s\n' "$current_version" "$required_version" | sort -V | head -n1)" == "$current_version" ]] && [[ "$current_version" != "$required_version" ]]; then
-    echo -e "\033[32mLa versión actual de sudo es $current_version, que es menor que $required_version. Procediendo con la actualización...\033[0m"
+    echo -e "\033[32mCurrent sudo version is $current_version, which is lower than $required_version. Proceeding with update...\033[0m"
     
     echo ""
     echo -e "\033[36m_________________________________________________________\033[0m"
     echo ""
 
-    # Ejecutar el proceso de actualización de sudo
+    # Update sudo
     sudo apt update
     #sudo apt install -y build-essential libpam0g-dev libssl-dev libselinux1-dev libtool pkg-config libaudit-dev libbsd-dev autoconf automake 
 
@@ -96,30 +93,29 @@ if [[ "$(printf '%s\n' "$current_version" "$required_version" | sort -V | head -
     sudo make install
 
     echo ""
-    echo -e "\033[33mActualización completada.\033[0m"
+    echo -e "\033[33mUpdate completed.\033[0m"
     echo ""
     echo -e "\033[36m_________________________________________________________\033[0m"
     echo ""
 
-    # Preguntar al usuario si desea reiniciar el sistema
-    read -p $'\033[35m¿Deseas cerrar sesion? [y/n]: \033[0m' choice
+    # Ask user if they want to log out
+    read -p $'\033[35mDo you want to log out now? [y/n]: \033[0m' choice
 
     echo ""
     echo -e "\033[36m_________________________________________________________\033[0m"
     echo ""
 
     if [[ "$choice" =~ ^[yY]$ ]]; then
-    echo -e "\033[31mCerrando la sesión actual...\033[0m"
-    pkill -KILL -u $USER
+        echo -e "\033[31mLogging out current session...\033[0m"
+        pkill -KILL -u $USER
     else
-        echo -e "\033[33mOperación cancelada.\033[0m"
+        echo -e "\033[33mOperation cancelled.\033[0m"
     fi
 
 else
-    echo -e "\033[34mLa versión actual de sudo es $current_version, que es mayor o igual a $required_version. No es necesaria la actualización.\033[0m"
+    echo -e "\033[34mCurrent sudo version is $current_version, which is greater or equal to $required_version. No update needed.\033[0m"
     echo ""
     echo -e "\033[36m_________________________________________________________\033[0m"
     echo ""
     exit 0
 fi
-
