1

diff --git a/binarios/gatin b/binarios/gatin
--- a/binarios/gatin
+++ b/binarios/gatin
@@ -1,14 +1,16 @@
 #!/bin/bash
 
+# Check if the hash file is provided
 if [ -z "$1" ]; then
-    echo "Usage: $0 <hash_file>"
+    echo -e "\033[31mUsage: $0 <hash_file>\033[0m"
     exit 1
 fi
 
+# Display hash modes
 echo -e "\n\033[1;32m_________________________________________________________\033[0m\n"
-echo "Which hash algorithm do you want to use?"
+echo -e "\033[34mWhich hash algorithm do you want to use?\033[0m"
 echo -e "\n\033[1;32m_________________________________________________________\033[0m\n"
-echo "1. MD5 (Mode: 0)"
+echo -e "\033[33m1. MD5 (Mode: 0)"
 echo "2. SHA-1 (Mode: 100)"
 echo "3. SHA-256 (Mode: 1400)"
 echo "4. NTLM (Mode: 1000)"
@@ -16,81 +18,45 @@ echo "5. WPA/WPA2 (Mode: 22000)"
 echo "6. bcrypt (Mode: 3200)"
 echo "7. Unix Crypt (Mode: 500)"
 echo "8. MySQL (Mode: 300)"
-
+echo "9. Kerberos 5, etype 23, AS-REP (Mode: 18200)\033[0m"
 echo -e "\n\033[1;37m_________________________________________________________\033[0m\n"
-read -n1 -p "Enter the mode number: " mode
 
+# Get user input for mode
+read -n2 -p "Enter the mode number: " mode
 echo ""
 echo "_________________________________________________________"
 echo ""
 
-echo -e "\e[34m"
-echo "Hashcat will now attempt to crack the hash using all dictionaries"
-echo "found in /usr/share/wordlists/4rji"
+# Attempt to crack the hash using hashcat
+echo -e "\033[34mHashcat will now attempt to crack the hash using all dictionaries found in /usr/share/wordlists/4rji\033[0m"
 ls -l /usr/share/wordlists/4rji
-echo -e "\e[0m"
+echo ""
 
-
-echo -e "\n\033[1;31m_________________________________________________________\033[0m\n"
-
-hashcat -m 22000 -w 3 "blasd.hc22000" /usr/share/wordlists/4rji/*
-
-sleep 1
 case $mode in
-    1)
-        echo "Command to execute: hashcat -m 0 \"$1\" /usr/share/wordlists/4rji/*"
-        hashcat -w 3 -m 0 "$1" /usr/share/wordlists/4rji/*
-        ;;
-    2)
-        echo "Command to execute: hashcat -m 100 \"$1\" /usr/share/wordlists/4rji/*"
-        hashcat -w 3 -m 100 "$1" /usr/share/wordlists/4rji/*
-        ;;
-    3)
-        echo "Command to execute: hashcat -m 1400 \"$1\" /usr/share/wordlists/4rji/*"
-        hashcat -w 3 -m 1400 "$1" /usr/share/wordlists/4rji/*
-        ;;
-    4)
-        echo "Command to execute: hashcat -m 1000 \"$1\" /usr/share/wordlists/4rji/*"
-        hashcat -w 3 -m 1000 "$1" /usr/share/wordlists/4rji/*
-        ;;
-    5)
-        echo "Command to execute: "
-        echo "hashcat -w 3 -m 22000 \"$1\" /usr/share/wordlists/4rji/*"
-        sleep 2
-        echo -e "\n\033[1;31m_________________________________________________________\033[0m\n"
-        hashcat -w 3 -m 22000 "$1" /usr/share/wordlists/4rji/*
-        ;;
-    6)
-        echo "Command to execute: hashcat -m 3200 \"$1\" /usr/share/wordlists/4rji/*"
-        hashcat -w 3 -m 3200 "$1" /usr/share/wordlists/4rji/*
-        ;;
-    7)
-        echo "Command to execute: hashcat -m 500 \"$1\" /usr/share/wordlists/4rji/*"
-        hashcat -w 3 -m 500 "$1" /usr/share/wordlists/4rji/*
-        ;;
-    8)
-        echo "Command to execute: hashcat -m 300 \"$1\" /usr/share/wordlists/4rji/*"
-        hashcat -w 3 -m 300 "$1" /usr/share/wordlists/4rji/*
-        ;;
-    *)
-        echo "Invalid mode number. Exiting."
-        exit 1
-        ;;
+    1) hashcat -w 3 -m 0 "$1" /usr/share/wordlists/4rji/* ;;
+    2) hashcat -w 3 -m 100 "$1" /usr/share/wordlists/4rji/* ;;
+    3) hashcat -w 3 -m 1400 "$1" /usr/share/wordlists/4rji/* ;;
+    4) hashcat -w 3 -m 1000 "$1" /usr/share/wordlists/4rji/* ;;
+    5) hashcat -w 3 -m 22000 "$1" /usr/share/wordlists/4rji/* ;;
+    6) hashcat -w 3 -m 3200 "$1" /usr/share/wordlists/4rji/* ;;
+    7) hashcat -w 3 -m 500 "$1" /usr/share/wordlists/4rji/* ;;
+    8) hashcat -w 3 -m 300 "$1" /usr/share/wordlists/4rji/* ;;
+    9) hashcat -w 3 -m 18200 "$1" /usr/share/wordlists/4rji/* ;;
+    *) echo -e "\033[31mInvalid mode number. Exiting.\033[0m"
+       exit 1 ;;
 esac
 
-ejecutar_comando_si_s() {
-    read -p "see the hashes? (s/n): " respuesta
+# Function to ask user if they want to see cracked hashes
+function ejecutar_comando_si_s {
+    read -p "See the hashes? (s/n): " respuesta
     if [ "$respuesta" = "s" ]; then
         echo -e "\n\033[1;32m_________________________________________________________\033[0m\n"
-        # Mostrar el comando para ver los hashes crackeados
-        echo "Command to view cracked hashes: hashcat --show $1"
-        echo -e "\n\033[1;32m_________________________________________________________\033[0m\n"
+        echo -e "\033[34mCommand to view cracked hashes: hashcat --show $1\033[0m"
         hashcat --show $1
     else
         echo "No se ejecutará el comando."
     fi
 }
 
-# Llamar a la función y pasarle el argumento necesario
+# Call the function and pass the necessary argument
 ejecutar_comando_si_s "$1"
-
