1

diff --git a/binarios/iniciar2 b/binarios/iniciar2
--- a/binarios/iniciar2
+++ b/binarios/iniciar2
@@ -1,12 +1,17 @@
 #!/bin/bash
 
+# Verificar si la variable maquina está definida
+if [ -z "$maquina" ]; then
+  echo "Error: La variable 'maquina' no está definida en el entorno."
+  exit 1
+fi
+
 # Verificar si se proporcionó el nombre de la máquina
 if [ -z "$1" ]; then
   echo "Error: No se proporcionó el nombre de la máquina."
   echo "Uso: $0 <nombre_maquina>"
   exit 1
 fi
-
 
 iniciar() {
   local base_dir="/home/ass/Documents/GitHub/4rji/4rjinotes/htb"
@@ -18,7 +23,7 @@ iniciar() {
   # Crear directorio y copiar plantilla
   mkdir -p "$new_dir" && cd "$new_dir" && mkdir -p nmap content exploits scripts && cp "$template_file" "$machine_name.md"
 
-  # Abrir primera ventana de Kitty en el directorio ra  z
+  # Abrir primera ventana de Kitty en el directorio raíz
   kitty @ launch zsh -c "cd \"$new_dir\"; exec zsh"
 
   # Abrir segunda ventana de Kitty en el directorio nmap
@@ -33,4 +38,4 @@ iniciar() {
 }
 
 # Llamar a la función iniciar con el nombre de la máquina como argumento
-iniciar "$1"
+iniciar "$maquina"
