1

diff --git a/binarios/wireinst b/binarios/wireinst
--- a/binarios/wireinst
+++ b/binarios/wireinst
@@ -91,38 +91,51 @@ setup_wireguard() {
     echo ""
 }
 
-# Check if the configuration file was provided as an argument
-echo -e "\033[0;32m"
-echo "_________________________________________________________"
-echo ""
-if [ "$#" -eq 0 ] || ([ "$#" -eq 1 ] && [ "$1" != "-c" ]); then
-    echo -e "\033[0;31mError: No configuration file provided."
-    echo -e "Usage: $0 [-c] path/to/file.conf\033[0m"
-    exit 1
-fi
-echo -e "\033[0m"
 
-# Check for the -c option
+
+#!/bin/bash
+
+# Function to handle the setup of the WireGuard connection
+setup_wireguard() {
+    echo -e "\033[0;34mCopying the configuration file to /etc/wireguard/\033[0m"
+    # Copy the configuration file to the WireGuard directory
+    sudo cp "$config_file" "/etc/wireguard/$file_name"
+    # Adjust configuration file permissions
+    sudo chmod 600 "/etc/wireguard/$file_name"
+
+    echo -e "\033[0;35mBringing up the WireGuard connection...\033[0m"
+    # Bring up the WireGuard connection
+    sudo wg-quick up "$interface_name"
+
+    echo -e "\033[0;36mCurrent status of WireGuard:\033[0m"
+    # Display WireGuard status
+    sudo wg
+    echo ""
+
+    echo "Connecting."
+    sleep .5
+    echo "Connecting.."
+    sleep 1
+    echo ""
+
+    echo -e "\033[0;31mYour public IP address is:\033[0m"
+    # Display the public IP address
+    curl ifconfig.me
+    echo ""
+}
+
+# Check if -c flag is present or a configuration file is provided
 if [ "$1" == "-c" ]; then
-    skip_setup=true
-    config_file=$2
+    crontab_mode=true
+elif [ -z "$1" ]; then
+    echo -e "\033[0;31mError: No configuration file provided or -c flag not used."
+    echo -e "Usage: $0 [-c | path/to/file.conf]\033[0m"
+    exit 1
 else
     config_file=$1
-fi
-
-# Extract the base name of the file to use in the commands
-file_name=$(basename "$config_file")
-
-# If not skipping setup, then perform setup
-if [ "$skip_setup" != true ]; then
-    setup_wireguard
-fi
-
-# Extract interface name from file name
-if [[ $file_name == *.conf ]]; then
+    file_name=$(basename "$config_file")
     interface_name="${file_name%.*}"
-else
-    interface_name="$file_name"
+    setup_wireguard
 fi
 
 # Ask the user about adding to crontab
@@ -140,8 +153,13 @@ else
     echo "No changes have been made to the crontab."
 fi
 
+
 echo -e "\n\033[1;33m_________________________________________________________\033[0m\n"
 
 echo -e "\033[1;37mADVISORY: This script should be used for authorized penetration testing and/or educational purposes only. Any misuse of this software will not be the responsibility of the author or of any other collaborator. Use it at your own computers and/or with the computer owner's permission.\033[0m"
 
+echo -e "\n\033[1;33m_________________________________________________________\033[0m\n"
+
+echo ""
+crontab -l
 echo ""
